version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: gestion_archivos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_archivos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gestion_archivos_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion_archivos_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_archivos
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - gestion_archivos_network

volumes:
  mysql_data:

networks:
  gestion_archivos_network:
    driver: bridge
